### ISSUE TITLE
Can't resolve worker threads

### ISSUE THREAD

**Issue by mpaccione** [jscastro76/threebox#223] opened 2021-04-05 23:26 UTC
Hello, I am using Webpack on clientside. I have no issues with my other packages.
I am receiving this error.

Working with my public repo here:
https://github.com/mpaccione/everest_flight_sim/tree/debugger-mapbox-tiles

in /client dir
npm install
edit dirname path in webpack.config.js
npm run build

Any thoughts on the issue? Also, unless I import Three myself I get this error: Error: THREE is not defined
    at eval (mapbox-gl.js:30)

```
WARNING in ./node_modules/threebox-plugin/src/objects/fflate.min.js 6:538-570
Module not found: Error: Can't resolve 'worker_threads' in 'C:\Projects\everest_flight_sim\client\node_modules\threebox-plugin\src\objects'
resolve 'worker_threads' in 'C:\Projects\everest_flight_sim\client\node_modules\threebox-plugin\src\objects'
  Parsed request is a module
  using description file: C:\Projects\everest_flight_sim\client\node_modules\threebox-plugin\package.json (relative path: ./src/objects)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      looking for modules in C:/Projects/everest_flight_sim/client/node_modules
        single file module
          using description file: C:\Projects\everest_flight_sim\client\package.json (relative path: ./node_modules/worker_threads)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\everest_flight_sim\client\node_modules\worker_threads doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\everest_flight_sim\client\node_modules\worker_threads.js doesn't exist
            .json
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\everest_flight_sim\client\node_modules\worker_threads.json doesn't exist
            .wasm
              Field 'browser' doesn't contain a valid alias configuration
              C:\Projects\everest_flight_sim\client\node_modules\worker_threads.wasm doesn't exist
        C:\Projects\everest_flight_sim\client\node_modules\worker_threads doesn't exist
ModuleNotFoundError: Module not found: Error: Can't resolve 'worker_threads' in 'C:\Projects\everest_flight_sim\client\node_modules\threebox-plugin\src\objects'
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\Compilation.js:1668:28
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:712:13
    at eval (eval at create (C:\Projects\everest_flight_sim\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:273:22
    at eval (eval at create (C:\Projects\everest_flight_sim\client\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:9:1)
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:402:22
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:117:11
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:628:24
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:782:8
    at C:\Projects\everest_flight_sim\client\node_modules\webpack\lib\NormalModuleFactory.js:902:5
 @ ./node_modules/threebox-plugin/src/objects/loaders/FBXLoader.js 2:15-42
 @ ./node_modules/threebox-plugin/src/objects/loadObj.js 9:18-51
 @ ./node_modules/threebox-plugin/src/Threebox.js 17:15-46
 @ ./node_modules/threebox-plugin/main.js 2:14-39
 @ ./src/index.mjs 7:0-43 11:12-20 308:18-26 311:22-30

2021-04-05 16:22:59: webpack 5.30.0 compiled with 1 warning in 5451 ms (77006e2629a9e3bbfaba)
```

**Comment by jscastro76** [comment] 2021-04-06 05:54
Hi @mpaccione,
Thanks for using Threebox!
The problem seems to be with the reference of `worker_theeads` required from `fflate`, currently needed for the new `FBXLoader` included in threejs r127.  
I’ll take a look to it

**Comment by jscastro76** [comment] 2021-04-06 11:17
I was able to solve it in my bundle with browserify, ignoring the reference using `browserify --i worker_threads`, so I guess you should have an equivalent command in webpack. BTW, [I've just opened an issue in fflate repo](https://github.com/101arrowz/fflate/issues/51), to see if there's any option to solve it from the file itself

**Comment by jscastro76** [comment] 2021-04-06 14:14
I have found a workaround, and apparently it works also with browserify without adding any ignore parameter and of course still functional for the browser use. 

Editing the `fflate.min.js` file...
```js
/// instead of var e = {}, assign e to eval
function(_f){"use strict";var e=eval;...

///then... use the e to eval the require first 
  try{e("require('worker_threads')").Worker}
```

I'm uploading this change now, but it won't be yet at the published module version in npm until v2.2.2

**Comment by mpaccione** [comment] 2021-04-07 00:04
Hi JS,

Thanks for such a quick response on this. 
I'm glad that this issue has been resolved in the future version.

I'm unsure whether or not the warning prevents the code from executing because the build still compiles. I will say that using Webpack I seriously cannot run this npm package as an ES6 module import. I had specifically moved away from browserify to webpack and I do not plan to go back after putting the time in already. Overall I'm not a fan of commonJS modules.

Anyways, I want you to know that in my webpack configuration all the other modules work. The official Three js and Mapbox modules work. Threebox definitely absolutely is a no go on my import. My backup plan is to include it in the .html file but...fwiw it may be something to check into. I'm not a webpack expert but since my other modules check out... 

import { Threebox } from "threebox-plugin/dist/threebox.js"; 
This results in UNDEFINED 

import { Threebox } from "threebox-plugin";
This results in  Error: THREE is not defined at eval (mapbox-gl.js:30)

**Comment by jscastro76** [comment] 2021-04-07 06:58
@mpaccione that's up to you, I'm not pretending you to use Threebox! 

But just to clarify, the issue is not in Threebox, it's in `THREE.FBXLoader`. You surely can import Three.js because it doesn't include `THREE.FBXLoader` but you'll have the same issue if you try to bundle it to load `.fbx` objects. Indeed, as you can see in the issue I opened at fflate, [the owner of the repo already foresaw the problem](https://github.com/101arrowz/fflate/issues/51#issuecomment-814197995) when started to collaborate with threejs, because the issue is in the minified version of fflate, `fflate.min.js`... read below...

> Actually, I foresaw this issue and provided an unminified ESM build and an unminified CJS build to avoid the problem. I was hoping that nobody would ever use Webpack on the UMD build; it was meant specifically for direct users. Could you try [replacing this line](https://github.com/jscastro76/threebox/blob/master/src/objects/loaders/FBXLoader.js#L2) with a `require` call to [this CJS build](https://cdn.jsdelivr.net/npm/fflate/lib/browser.js)?

I was about to report the issue to threejs, but I think it doesn't deserve the time as I have already solved it here, and you decide  not to use threebox, which is perfectly fine!

Closing this issue then!

**Closed by jscastro76** 2021-04-07 06:58 UTC
Labels: :beetle: bug

**Comment by jscastro76** [comment] 2021-04-11 12:35
@mpaccione this is already uploaded to v.2.2.2 version of the npm module if you want to use it

**Comment by mpaccione** [comment] 2021-04-14 00:35
@jscastro76 Nice work on the worker_threads fix. I had tested 2.2.1 out on both Linux and Windows. It was only my Windows machine that threw the error. Now in 2.2.2 it is no problem. 

Thank you kindly and looking forward to learning more about Threebox.

**Comment by jscastro76** [comment] 2021-04-15 07:24
Not sure what's the issue you're facing, the module is imported properly in [ten other projects](https://github.com/jscastro76/threebox/network/dependents?package_id=UGFja2FnZS0xNTY1ODM5MTQ3). 

you have also [an example in vue.js](https://codesandbox.io/s/vue-threebox-sample-forked-loi44?file=/src/components/ThreeboxExample.vue) that uses threebox as a module.

Regarding THREE, is bundled in Threebox, so it should be accessible using 
```js
import {THREE} from "threebox-plugin"
```
or
```js
import {THREE} from "threebox-plugin/dist/threebox.js"
```
Hope it helps
