### ISSUE TITLE
Module not found: Can't resolve 'worker_threads'

### ISSUE THREAD

**Issue by DevArt002** [jscastro76/threebox#230] opened 2021-04-10 17:25 UTC
I open this issue because I see warning during development. I installed `2.2.1` version of `threebox-plugin`. When I used `2.1.9`, there was no such warning. I'd love to fix that:

```
./node_modules/threebox-plugin/src/objects/fflate.min.js
Module not found: Can't resolve 'worker_threads' in '...\node_modules\threebox-plugin\src\objects'
```

![warning](https://user-images.githubusercontent.com/52213952/114278954-c2af9680-9a3a-11eb-90ee-5f051b83ed32.PNG)

**Comment by jscastro76** [comment] 2021-04-10 17:31
I think this one is repeated with #223, not a bug of Threebox, but a bug in `fflate` minimized version included in three.js, as stated by the owner of `fflate`. 

It's already solved for the next version v2.2.2 to be published tomorrow as npm, already resolved in code.

**Comment by DevArt002** [comment] 2021-04-10 17:33
Perfect. Thank you so much!

**Comment by jscastro76** [comment] 2021-04-10 17:42
Thanks @DevArt002 for reporting them properly, as you can see, it helps a lot to identify and resolve the issues.

Versions v2.2.1 and v2.2.2 are including the most important changes in Threebox in a year as v2.2.1 meant the update from Three.js from r117 to r127, and v2.2.2 will include the update from Mapbox 1.11.1 to 2.2.0

**Comment by DevArt002** [comment] 2021-04-10 17:57
Great job! I can't wait to see v2.2.2.
By the way, there will be changes on the threebox documentation?

**Comment by jscastro76** [comment] 2021-04-10 18:08
> Great job! I can't wait to see v2.2.2.
> By the way, there will be changes on the threebox documentation?

I'm updating what is changing, but there could be some things I missed (documentation is every day bigger and it's always work in progress). If you find anything that is not updated, please let me know.

**Comment by DevArt002** [comment] 2021-04-10 18:15
Yup, I will. Whenever I find issues regarding threebox-plugin, I will never hesitate to open it. 
Thank you!

**Closed** 2021-04-11 11:55 UTC
Labels: :beetle: bug, :dancers: duplicated

**Comment by jscastro76** [comment] 2021-04-11 12:20
Please @DevArt002 check if the new module v2.2.2 has solved your issue

**Comment by DevArt002** [comment] 2021-04-12 00:42
Awesome! Thank you. 
v2.2.2 solved my problems!
